# See http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: java
jdk: oraclejdk8
sudo: required
services: docker
env:
  global:
    - secure: iiLLSV0SZIQjiJFtHgNvshUXzPBT/DeEFYWpVTfQz3txJyew+AIcC/G8JxajeJQunOXP/Wz1f2UFpQJpWBHN9dn0RlWgxzQ6gadyXsRhO277OUW4NgvqDLESq7zNgtl4TR9gZ7gieNFq8x9vMwqJ3RNtTyCcKO4WK/3Jtcgcjz4=
    - secure: LcqLewIdxfPkvGp+5x84GfG0Ga1KhXAXAJtRrydvUhtN1+qRV/7nNxmwYh7uRbLvj5AK5FcxG6musNNfMpCwbeUswkXCMk1PSLigvwvcF48IzD970kEfpuK3OgkAdGrsGwo9lwO5s+V/Uy0wgroPYov9wokchpEa8RTXFCAsuLc=
    - secure: GyXsJsLmQLn264RtAPzs7sW/HYJqig1brzbLkrwMZXhUk7z2mt8Ng3BKRKiDYO4g1GKakg/fUzbyWyPFDbg21C26t9RhU6L4ZuiM+CtXFotue77ZKBf704M3wkt610Ht4WQ8GsEoTFWnFbTuu2jL9VovCU78HhKE8YnslNBsIL0=
    - COMMIT=${TRAVIS_COMMIT::8}

install: true
script: mvn clean test
after_success:
  - mvn site
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=urbanetic/aurin-acs
  - export VERSION=$(mvn -o org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v '\[')
  # Convert branch names to lower case and replace slashes
  - export TAGS=$(if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest $VERSION"; else echo $TRAVIS_BRANCH | sed 's#/#_#g' | tr '[:upper:]' '[:lower:]' ; fi)
  - mvn package docker:build -DskipTests -DpushImage -DpushImageTags $(printf " -DdockerImageTag=%s" $TAGS)

# Deploy JavaDocs to S3 static site.
# See http://docs.travis-ci.com/user/deployment/s3/
deploy:
  provider: s3
  # Access key is the public key.
  access_key_id: AKIAJCBJHLNERAVXIURA
  # Secret access key is the private key, encrypted for Travis.
  secret_access_key:
    secure: X5NDAzi8AoIPIgZ5GeFScuVQzHzX88iyvLpxGWbUmfqyR8o0n/4dCciuWMiEI4LnHXox9QiFf/L1/p6nYjf8pUSjqLWsQDWw+1HWjhNQ7f6mRnG2X9DFEq/qtOL40iGVt0+HewJaCBYUZMDFoXVdGdiTVPydJioMH7wU4J2QsR0=
  bucket: javadocs.acs.urbanetic.net
  endpoint: javadocs.acs.urbanetic.net.s3-website-ap-southeast-2.amazonaws.com
  region: ap-southeast-2
  local-dir: target/site/apidocs
  skip_cleanup: true
  on:
    all_branches: true
