# HTTP server settings.
http:
  bindHost: 0.0.0.0
  port: 8090
  adminPort: 8092

# Logging settings.
logging:
  level: DEBUG
  file:
    enabled: true
    currentLogFilename: /var/aurin/acs/log/acs.log
    archivedLogFilenamePattern: /var/aurin/acs/log/acs-%d.log.gz

bimserver:
  host: http://localhost:8080/bimserver
  username: admin@bimserver.org
  password: admin
