# HTTP server settings.
http:
  port: 8081
  adminPort: 8082

# Logging settings.
logging:
  level: DEBUG
  file:
    enabled: true
    currentLogFilename: /var/aurin/acs/log/acs.log
    archivedLogFilenamePattern: /var/aurin/acs/log/acs-%d.log.gz

bimserver:
  host: http://localhost:8080
  username: admin@bimserver.org
  password: admin