site_name: Asset Conversion Service
repo_url: https://github.com/urbanetic/aurin-acs

site_description: Documentation for the Asset Conversion Service component of the AURIN Volumetric Module.
site_author: Oliver Lade
site_favicon: img/favicon.png

pages:
- ['index.md', 'Introduction']
- ['api.md', 'API']
- ['design.md', 'Design']
- ['developers.md', 'Developers']
- ['license.md', 'License']
